workspace(name = "com_github_ericnorris_rules_nfpm")

load("//nfpm:repositories.bzl", "rules_nfpm_dependencies")

rules_nfpm_dependencies()

load("//nfpm:setup.bzl", "rules_nfpm_setup")

# the nogo parameter is not needed by users of rules_nfpm
rules_nfpm_setup(nogo = "@//:rules_nfpm_nogo")

load("//nfpm:go_repositories.bzl", "rules_nfpm_go_dependencies")

# gazelle:repository_macro deps.bzl%go_dependencies
rules_nfpm_go_dependencies()


#
# Dependencies not needed by users of rules_nfpm
#

# load("//nfpm/internal:repositories.bzl", "rules_nfpm_internal_dependencies")

# rules_nfpm_internal_dependencies()

# load("//nfpm/internal:setup.bzl", "rules_nfpm_internal_setup")

# rules_nfpm_internal_setup()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
     name = "rules_python",
     sha256 = "2cc26bbd53854ceb76dd42a834b1002cd4ba7f8df35440cf03482e045affc244",
     strip_prefix = "rules_python-1.3.0",
     url = "https://github.com/bazel-contrib/rules_python/releases/download/1.3.0/rules_python-1.3.0.tar.gz",
 )

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

http_archive(
     name = "io_bazel_stardoc",
     sha256 = "0e1ed4a98f26e718776bd64d053d02bb34d98572ccd03d6ba355112a1205706b",
     urls = [
         "https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/0.7.2/stardoc-0.7.2.tar.gz",
         "https://github.com/bazelbuild/stardoc/releases/download/0.7.2/stardoc-0.7.2.tar.gz",
     ],
 )

load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")

stardoc_repositories()

load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@io_bazel_stardoc//:deps.bzl", "stardoc_external_deps")

stardoc_external_deps()

load("@stardoc_maven//:defs.bzl", stardoc_pinned_maven_install = "pinned_maven_install")

stardoc_pinned_maven_install()
